"""add due_date and actual_completion_date to timesheets

Revision ID: 955bc45e14df
Revises: 89801ea2cc5f
Create Date: 2026-08-17 15:30:59.568566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955bc45e14df'
down_revision: Union[str, Sequence[str], None] = '89801ea2cc5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheets', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('timesheets', sa.Column('actual_completion_date', sa.Date(), nullable=True))
    op.alter_column('timesheets', 'subtask_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timesheets', 'subtask_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('timesheets', 'actual_completion_date')
    op.drop_column('timesheets', 'due_date')
    # ### end Alembic commands ###
